# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: nutee-back

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  S3_BUCKET_NAME: nutee-storage
  PROJECT_NAME: nutee-back

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.8

    - name: Grant execute permissions
      run: chmod +x gradlew scripts/deploy.sh
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash

    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://nutee-storage/nutee-back/$GITHUB_SHA.zip

    - name: Code Deploy
      run : aws deploy create-deployment --application-name nutee-back --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name nutee --s3-location bucket=nutee-storage,bundleType=zip,key=nutee-back/$GITHUB_SHA.zip
